---
title: "IFQ Bottom Trawl Mortality Rates"
author: "Jason E. Jannot"
date: "`r Sys.Date()`"
---

```{r eval=TRUE, echo=FALSE, message=FALSE, warnings=FALSE, results='hide'}
knitr::opts_chunk$set( echo = FALSE,
                       warnings = FALSE,
                       message = FALSE,
                       include = TRUE)
```

```{r btwlIFQmortrates, eval=TRUE, echo=FALSE, include=TRUE, results='asis'}

btwlmortrates <- read.csv(file = paste0(drive, "data/AE_IFQ_Btwl_MortRates.csv"),
                        header = TRUE, stringsAsFactors = FALSE)%>%
                 slice(2:nrow(.))%>%
                 setNames(., nm = slice(., 1))%>%
                 slice(2:nrow(.))%>%
                 mutate(Mortality_Rate = sprintf("%.2f", as.numeric(Mortality_Rate)),
                              Sector = "Catch Shares")%>%
                 dplyr::select(Sector, Gear, everything())%>%
                 qdf()

flxtbl_fxn(btwlmortrates, hdrs = list(Sector = "Sector", 
                                      Gear = "Gear",
                                      Viability = "Viability",
                                      Mortality_Rate = "Mortality Rate"))%>%
            flextable::merge_v(., j = "Sector")%>%
            flextable::merge_v(., j = "Gear")%>%
            flextable::autofit() 
 
```


